site_name: SeaWars Documentation
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.code.annotate 

nav:
  - Introduction: index.md
  - The Arena:
    - The Board: arena/board.md
    - Game Entities: arena/entities.md
    - The Bot: arena/bots.md
  - Game Mechanics:
    - Perception : mechanics/perception.md
    - Actions & Abilities : mechanics/actions_and_abilities.md
    - Resolution Rules: mechanics/resolution.md
    - Winning the Game: mechanics/win_conditions.md
  - Bot Development (SDK):
    - Setup & Structure: sdk/setup.md
    - Writing Your Bot: sdk/writing_bots.md
    - Build Your First Bot: sdk/first_bot.md
    - Debugging & Logs: sdk/debugging.md
  - API Reference:
    - GameAPI: api_reference/game_api.md
    - BotController: api_reference/bot_controller.md
    - BotContext: api_reference/bot_context.md
    - Utilities: api_reference/utilities.md
  - Glossary:
    - Glossary: glossary/glossary.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets